name: X86_64 Immortalwrt

on:
  workflow_dispatch:
    inputs:
      subnet:
        description: "é»˜è®¤IPåœ°å€:192.168.[].1"
        required: true
        default: "2"
  schedule:
    - cron: '0 22 * * 5' # æ¯å‘¨å…­ 6:00ï¼ˆåŒ—äº¬æ—¶é—´ï¼‰è‡ªåŠ¨ç¼–è¯‘

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: x86_imm/x86.config
  CUSTOM_SCRIPT: x86_imm/custom.sh
  CACHE_TOOLCHAIN: true
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: X86_64
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
    - name: ğŸ–¥ï¸ æ£€æŸ¥æœåŠ¡å™¨æ€§èƒ½
      run: |
        echo "è­¦å‘Šâš "
        echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
        echo -e "å·²çŸ¥CPUå‹å·(é™åº): 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "--------------------------CPUä¿¡æ¯--------------------------"
        echo "CPUç‰©ç†æ•°é‡: $(nproc --all | grep -c '^')"
        echo "CPUæ ¸å¿ƒæ•°é‡: $(nproc)"
        echo -e "CPUå‹å·ä¿¡æ¯:$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo)\n"
        echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯: $(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: ğŸ—‚ï¸ æœ€å¤§åŒ–å¯ç”¨ç©ºé—´
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 100
        root-reserve-mb: 1024

    - name: âš™ï¸ åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204) rename clang libclang-dev llvm-dev
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"

    - name: â¬‡ï¸ æ£€å‡ºä»“åº“
      uses: actions/checkout@main

    - name: ğŸ“¦ å…‹éš† OpenWrt æºç 
      run: |
        git clone --depth=1 --single-branch $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

    - name: ğŸ”§ ç”Ÿæˆè®¾å¤‡å˜é‡
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig > /dev/null 2>&1
        
        # æå–æºç ä»“åº“åï¼ˆä¾‹å¦‚ AutoBuild-OpenWrtï¼‰
        echo "SOURCE_REPO=$(echo $REPO_URL | awk -F '/' '{print $(NF)}')" >> $GITHUB_ENV

        # æå–è®¾å¤‡ä¸»æ¶æ„ï¼ˆä¾‹å¦‚ x86ã€qualcommaxï¼‰
        echo "DEVICE_TARGET=$(grep CONFIG_TARGET_BOARD .config | awk -F '\"' '{print $2}')" >> $GITHUB_ENV

        # æå–è®¾å¤‡å­æ¶æ„ï¼ˆä¾‹å¦‚ 64ã€ipq60xxï¼‰
        echo "DEVICE_SUBTARGET=$(grep CONFIG_TARGET_SUBTARGET .config | awk -F '\"' '{print $2}')" >> $GITHUB_ENV

        # æå–æ¶æ„åŒ…åï¼ˆä¾‹å¦‚ x86_64ã€aarch64_cortex-a53ï¼‰
        echo "DEVICE_ARCH=$(sed -n 's/^CONFIG_TARGET_ARCH_PACKAGES="\([^"]*\)"/\1/p' .config)" >> $GITHUB_ENV

        # æå–è®¾å¤‡å‹å·ï¼ˆä¾‹å¦‚ genericã€zn_m2ï¼‰
        echo "DEVICE_MODEL=$(sed -n 's/^CONFIG_TARGET_PROFILE="DEVICE_\([^"]*\)"/\1/p' .config)" >> $GITHUB_ENV
    
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          SUBNET="${{ github.event.inputs.subnet }}"
          [ -z "$SUBNET" ] && SUBNET="2"
        else
          SUBNET="2"
        fi
        echo "SUBNET=$SUBNET" >> $GITHUB_ENV        

    - name: ğŸ› ï¸ ç¼“å­˜å·¥å…·é“¾
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: ğŸŒ± æ›´æ–°å¹¶å®‰è£… feeds
      run: |
        cd $OPENWRT_PATH
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: ğŸ“œ åŠ è½½è‡ªå®šä¹‰é…ç½®å’Œè„šæœ¬
      env:
        SUBNET: ${{ env.SUBNET }}
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
        chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        chmod +x $CUSTOM_SCRIPT
        cd $OPENWRT_PATH/package/
        $GITHUB_WORKSPACE/scripts/Packages.sh
        $GITHUB_WORKSPACE/scripts/Handles.sh
        $GITHUB_WORKSPACE/$CUSTOM_SCRIPT

    - name: ğŸ“¥ ä¸‹è½½ä¾èµ–
      run: |
        cd $OPENWRT_PATH
        make defconfig
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: ğŸ› ï¸ ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd $OPENWRT_PATH
        mkdir -p files/etc/uci-defaults
        cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/999-init-settings
        cp $GITHUB_WORKSPACE/scripts/init-tailscale.sh files/etc/uci-defaults/99-init-tailscale
        echo "ä½¿ç”¨ $(nproc) æ ¸å¿ƒè¿›è¡Œç¼–è¯‘"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "FILE_DATE=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

    - name: ğŸ“Š æŸ¥çœ‹ç£ç›˜ç©ºé—´ä½¿ç”¨æƒ…å†µ
      if: always()
      run: df -hT

    - name: ğŸ“‚ æ•´ç†å¹¶æ‰“åŒ… artifacts
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        ls -l
        # echo "KERNEL=$(grep ^kernel *.manifest | cut -d- -f2-3 | tr -d ' ')" >> $GITHUB_ENV
        echo "KERNEL=$(grep '^kernel' *.manifest | sed -n 's/^kernel - \([0-9.]*\)~.*/\1/p')" >> $GITHUB_ENV
        cd $OPENWRT_PATH
        mkdir -p ./artifact/package ./artifact/buildinfo
        find ./bin/packages/ -type f \( -name "*.ipk" -o -name "*.apk" \) -exec cp -f {} ./artifact/package/ \;
        find ./bin/targets/ -type f \( -name "*.buildinfo" -o -name "*.manifest" \) -exec cp -f {} ./artifact/buildinfo/ \;
        cd ./artifact
        tar -zcf "${DEVICE_ARCH}_packages.tar.gz" package
        echo "å·²å®Œæˆ packages å‹ç¼©ï¼ŒKERNEL å˜é‡å·²å†™å…¥"

    - name: â¬†ï¸ ä¸Šä¼  Buildinfo Artifact
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_buildinfo
        path: ${{ env.OPENWRT_PATH }}/artifact/buildinfo/

    - name: â¬†ï¸ ä¸Šä¼  Packages Artifact
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_packages
        path: ${{ env.OPENWRT_PATH }}/artifact/packages.tar.gz

    - name: ğŸš€ ä¸Šä¼ å›ºä»¶åˆ° Release
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: ncipollo/release-action@main
      with:
        name: R${{ env.DATE }} for ${{ env.FIRMWARE_TAG }}
        allowUpdates: true
        tag: ${{ env.DEVICE_TARGET }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.OPENWRT_PATH }}/bin/targets/*/*/*.tar.gz, ${{ env.OPENWRT_PATH }}/bin/targets/*/*/*combined-efi.img.gz, ${{ env.OPENWRT_PATH }}/bin/targets/*/*/*.vmdk
        body: |
          ğŸ’» **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
          ### ğŸ“‹ å›ºä»¶ä¿¡æ¯
          -  ğŸ”§ å¹³å°æ¶æ„: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          -  ğŸ“¦ å›ºä»¶æºç : ${{ env.REPO_URL }}
          -  ğŸŒ¿ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
          -  âš™ï¸ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}

    - name: ğŸ“¢ å‘é€ Telegram é€šçŸ¥
      run: |
        TIME=$(TZ='Asia/Shanghai' date '+%Y/%m/%d %H:%M')
        MESSAGE="${{ env.FIRMWARE_TAG }} ç¼–è¯‘å®Œæˆ
        å‘å¸ƒæ—¶é—´: $TIME
        å‘å¸ƒé¡µé¢: https://github.com/${{ github.repository }}/releases/tag/Immortalwrt_${{ env.FIRMWARE_TAG }}"
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="$MESSAGE"
